name: Delta repository generator - SQLite variant
on:
  push:
    branches:
      - master
jobs:
  commit:
    runs-on: ubuntu-latest
    if: >-
      !(
        contains(github.event.head_commit.message, '[ci skip]') ||
        contains(github.event.head_commit.message, '[skip ci]') ||
        contains(github.event.head_commit.message, '[actions skip]') ||
        contains(github.event.head_commit.message, '[skip actions]')
      )
    env:
      REMOTE: ProjectIgnis/DeltaUtopia.git
      DESTINATION: DeltaUtopia
      BASE_SHA: 20201222
    steps:
    - uses: actions/checkout@v1
    - name: Install sqlite3
      run: |
        sudo apt update
        sudo apt install -y sqlite3
    - name: Clone destination repository
      run: |
        cd $HOME
        git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/$REMOTE
        mkdir -p $DESTINATION
    - name: Copy new CDBs only
      run: |
        ADDED=$(git diff --name-only --no-renames --diff-filter=A $BASE_SHA | grep ".cdb$" || [[ $? == 1 ]])
        if [[ "$ADDED" ]]; then
          rsync -avR $ADDED $HOME/$DESTINATION
        fi
    - name: Remove deleted files
      run: |
        if [[ -f $HOME/$DESTINATION/VERSION ]]; then
          LAST_SHA=$(cat $HOME/$DESTINATION/VERSION)
          REMOVED=$(git diff --name-only --no-renames --diff-filter=D $LAST_SHA)
          if [[ "$REMOVED" ]]; then
            cd $HOME/$DESTINATION
            git rm -rf --ignore-unmatch $REMOVED
          fi
        fi
    - name: Generate SQLite deltas
      run: |
        CHANGED=$(git diff --name-only --diff-filter=M $BASE_SHA | grep ".cdb$" || [[ $? == 1 ]])
        for DB in $CHANGED; do
          ./ci/sqlite3-git.sh $BASE_SHA $DB
        done
        find . -type f -name '*.delta.cdb' -exec rsync -avR {} $HOME/$DESTINATION \;
    - name: Commit and push with original metadata
      run: |
        MESSAGE=$(git log -1 --pretty=%B)
        AUTHOR=$(git log -1 --pretty=format:'%an')
        EMAIL=$(git log -1 --pretty=format:'%ae')
        COMMITTER=$(git log -1 --pretty=format'%cn')
        CEMAIL=$(git log -1 --pretty=format:'%ce')
        cd $HOME/$DESTINATION
        echo $GITHUB_SHA > VERSION
        git config user.email "$CEMAIL"
        git config user.name "$COMMITTER"
        git add -A .
        if [[ $(git status --porcelain) ]]; then
          git commit --author="$AUTHOR <$EMAIL>" -m "$MESSAGE"
          git push
        fi
